version: '3.8'

services:
  django:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=your_database_name
      - DB_USER=your_user
      - DB_PASSWORD=your_password
      - DB_HOST=postgres
      - DB_PORT=5432
    networks:
      - webnet
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - webnet
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    depends_on:
      - django
    networks:
      - webnet
networks:
  webnet:
volumes:
  static:
  postgres_data:
